{% set name = "GeoIP" %}
{% set version = "1.6.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/maxmind/geoip-api-c/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1dfb748003c5e4b7fd56ba8c4cd786633d5d6f409547584f6910398389636f80
  patches:
    - Makefile.vc.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make        # [unix]
    - m2-patch    # [win]
    - autoconf    # [unix]
    - automake    # [unix]
    - libtool     # [unix]

  host:
  run:

test:
  commands:
    - if not exist %LIBRARY_INC%\\{{ name }}.h exit 1    # [win]
    - if not exist %LIBRARY_LIB%\\{{ name }}.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\{{ name }}.dll exit 1  # [win]
    - test -f $PREFIX/include/{{ name }}.h               # [unix]
    - test -f $PREFIX/lib/lib{{ name }}.so               # [linux]
    - test -f $PREFIX/lib/lib{{ name }}.dylib            # [osx]

about:
  home: https://github.com/maxmind/geoip-api-c
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: 'GeoIP Legacy C Library'

  description: |
    The GeoIP Legacy C library enables the user to find geographical and
    network information of an IP address. To use this library, you may
    download our free GeoLite Legacy Country or City databases. These are
    updated at the beginning of every month.
  doc_url: https://github.com/maxmind/geoip-api-c
  dev_url: https://github.com/maxmind/geoip-api-c

extra:
  recipe-maintainers:
    - CJ-Wright
    - oschwald
