travis:
  secure:
    BINSTAR_TOKEN: oAicVVx9GF6kPrfc51QzAerrPv41NUXTK1FJ6uaoZRidivB1coxkhOdzjF3hqUGh58aYi66cqNVXr6MEXqZCWeXVV1NPfnHxOv4b7OeBTAgg8Uy/L4riCy+R2O4v0eOuEqHi8YxlB5F5aN32cmGXmNYrbldPTTLf+B+D2XLrlin39UDbbZftWPDiWlBfeN4SG+dcbKkrOapodY9W/u8+35BqkG3SMVLy7vH/4mO7PcdKeHSsUYlLAOUSCmQo3HXTTPsD4JmXCq+TlDbQpUx60VxpuIWbiBX4cWh0xtLCgoB5Klxt5I7/dm5ixlUkm21+Nga1230x3nj3yPjS9RAkxfjJHOxQ8Pv1+ZqrugMmRGvpijoEv/TDcW6Hy9JsZWL0cCdeppdKCnxOqekZIVbvlZZpiUzj4f6GA/x0mNo5CznY/UpgbK8CROf4Xv09IW8bB95+HdZ8oR8TMZ67nkTPFaiPC14cEuTYNYqJ5qqnTDMv1RYOVUAyye9zpgymVvMicgUcDNjNEbn6b2f6/jl+J05KmS7FQJHEiTqDaOkQDhBAmjWUdg/W52aEuOAnTf3m1arYjvOwp3AjhMAf6zI3WcC3zX2VL3eF0eZESCi8kAsMKypiGpCEm6HDubfNtZ4MPTowzLyl/7Hdj2IJaYoVjhWMSGLKNI6ZiOi0Ov2y0k0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
