appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mFXz6lyXaPv25mQKNyglELldKgd39O2tPogMD3Lz/wQFx8CP3qFeG3EynXWKDVyAeoZTerS6XDsoMk8kZmYYnLzou6xRFAzokN2h2ZFYr2wAF9n6510i9P3dIfGvziHdd95dIeMD1Tyun95c6f6n4f7tGRkDC6xdQK+ZxheElIdwfwjHTgfbvDhAN4++4QfY45yxcPYxA3HS1X2Jywl/Q1UT7dJdy8NID5/V3ATIjb6PnfJfajVmgSrTOzo/GjuOUFamGamKFacEhz3ly1yF21ci4/2LfRdulCtjuPjo1H0cXWJ8VDB8AS3Mv8IShpAIWV6tucylN2zKM+wbyPgF5xFd3KYwdGiB1sAPKqqLHfqUuVPlPfI2TDbd+ZLKPkjIchFVtKaYhe0fRFCyY4bMAURL1tw9wpsYYEpqEYwg3A41hq3jSWfgYeXkeUu8Yhp+NSpZ/w9O5d9r9G+svYbk+QlcGGhPySI4wr8W1ytWCOIfKog80MiUnHTpZNnITpCcIoj2rMPuV1Ve10wfsJqUD5XBnAoMyI6m6uBPGZDoNjduU7taz7whif6rN/eeknecGRW0RYzOCDZcE0EAM8fUeV6A0pXePPb5QS+WXii2D1aM+GNonoktGV5EL2LgJuQiJ8El1ij79QQSkMG21a7fwOniR1CuUPAHudaq1YQT5yc=}
conda_forge_output_validation: true
